
work_dir: /kaggle/working/work_dir/ntu120_xsub_2021_angular_train
feature_combo: bone
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /kaggle/working/Two-Stream-Angular-Skeleton-Encoding/data/ntu120/xsub/train_data_joint.npy
  label_path: /kaggle/working/Two-Stream-Angular-Skeleton-Encoding/data/ntu120/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /kaggle/working/Two-Stream-Angular-Skeleton-Encoding/data/ntu120/xsub/val_data_joint.npy
  label_path: /kaggle/working/Two-Stream-Angular-Skeleton-Encoding/data/ntu120/xsub/val_label.pkl

# model
model: model.network.Model
model_args:
  in_channels: 15
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # ablation
  ablation: sgcn_only

# optim
weight_decay: 0.0005
base_lr: 0.05
step: [35,45,55]

# training
num_epoch: 60
device: [0,1]
batch_size: 32
forward_batch_size: 32
test_batch_size: 32
nesterov: True

# 额外的
to_add_onehot: False
optimizer: SGD

# Pretrained models
# # This is to load the pretrained model, uncomment to use.
# weights: ""
# checkpoint: ""
# resume: True

eval_start: 1
eval_interval: 5
